name: uas_1
description: Aplikasi Cafe Management System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # QR Code Generation
  qr_flutter: ^4.1.0
  
  # Database
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # State Management
  provider: ^6.1.1
  
  # UI & Formatting
  intl: ^0.18.1
  
  # PDF Generation
  pdf: ^3.10.7
  
  # File Picker
  file_picker: ^6.1.1

  # Printing
  printing: ^5.12.0
  
  # Icons
  cupertino_icons: ^1.0.2

  fl_chart: ^0.65.0  # Library grafik yang powerful dan mudah
  syncfusion_flutter_charts: ^24.1.41  # Alternative (pilih salah satu)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Uncomment untuk menambahkan assets
  # assets:
  #   - assets/images/
  #   - assets/icons/